knowledge_repo/app/routes/index.py

Users' feed shows on the main feed page. 
Achieved by modifying DB query in serving page

Feed only shows a logged in users' feed

---

knowledge_repo/config_defaults.py
knowledge_repo/postprocessors/extract_images_to_s3.py

Changes needed to push things images to s3 and serve from there

---

application.py
knowledge_repo/app/index.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/routes/posts.py
knowledge_repo/repository.py

Changes needed to save time during post uploading

Ftr small index

---

knowledge_repo/app/routes/index.py

- Feed shows KR if argument is passed
- If not, it shows user their posts

Ftr folder feed

---

application.py
knowledge_repo/app/deploy/__init__.py
knowledge_repo/app/deploy/common.py
knowledge_repo/repositories/dbrepository.py
knowledge_repo/repository.py

DB calls are consolidated so that one connection is used

Fix db calls

---

knowledge_repo/app/templates/tag_pages.html

Fixed a missing bracket

---

knowledge_repo/app/routes/index.py

Fixed extra hit to API that would lead to error and time waste

---

knowledge_repo/app/routes/polly_api.py

If upload fails throw error page and not internal server error

Fix ipyformat error

---

application.py
knowledge_repo/app/deploy/common.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/repositories/dbrepository.py
knowledge_repo/repository.py

Changed pool size and connection limit

DB conneciton optimisation

---

knowledge_repo/app/routes/polly_api.py

Fix upload del

---

app_config.py
knowledge_repo/app/index.py
knowledge_repo/app/models.py
knowledge_repo/app/routes/polly_api.py

do an index less upload of posts and repos

Ftr avoid indexing

---

knowledge_repo/app/routes/polly_api.py
knowledge_repo/postprocessors/extract_images.py
knowledge_repo/repository.py

images are not ignored while uploading whole repos

 Fix upload images

---

app_config.py
knowledge_repo/app/app.py
knowledge_repo/app/routes/index.py
knowledge_repo/app/routes/polly_api.py

Ftr repos projectid

---

knowledge_repo/app/routes/posts.py
knowledge_repo/app/templates/markdown-base.html

Have a back button on the posts

Ftr back button

---

knowledge_repo/app/db_repo.py

The db_repo module was missing

Adding the DB_repo module which was missed out for some reason

---

.ebextensions/https-redirect-python.config
knowledge_repo/app/app.py
knowledge_repo/app/routes/index.py
knowledge_repo/app/routes/polly_api.py

Code to automatically make EB redirect HTTP requests to HTTPS

HTTPS redirection

---

knowledge_repo/app/app.py
knowledge_repo/app/routes/index.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/routes/stats.py
knowledge_repo/app/routes/tags.py
knowledge_repo/app/static/js/knowledge_typeahead.js
knowledge_repo/app/static/js/pages/base.js
knowledge_repo/app/templates/base.html
knowledge_repo/app/utils/posts.py
knowledge_repo/app/utils/requests.py

Reverts ElucidataInc/knowledge-repo#31

Revert "Search Feature"

---

.circleci/config.yml
eb_utils/.elasticbeanstalk/DEV_CONFIG_FILE.yml
eb_utils/.elasticbeanstalk/PROD_CONFIG_FILE.yml
eb_utils/.elasticbeanstalk/TEST_CONFIG_FILE.yml

changed file .circleci/config.yml to have autmatic CI/CD
created 3 files inside eb_utils/.ebrepository, one for each polly, devpolly and testpolly
currently code for automatic CI/CD for polly is commented for safety

Automatic CI/CD

---

knowledge_repo/app/app.py
knowledge_repo/app/routes/index.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/routes/stats.py
knowledge_repo/app/routes/tags.py
knowledge_repo/app/static/js/knowledge_typeahead.js
knowledge_repo/app/static/js/pages/base.js
knowledge_repo/app/templates/base.html
knowledge_repo/app/utils/posts.py
knowledge_repo/app/utils/requests.py

Description of changeset:
Completed the search feature for kr posts.
Supports nested search (search on the basis of query in the search bar given posts are already filtered on some other basis (like authors or kr etc)
Fixed recommendations shown while writing in search bar
Major Changes in files -
/utils/requests.py : Changed the function from_request_to_feed_params to from_url_to_feed_params. New function does the same task but with url instead of request
/utils/posts.py : get_posts function now filters posts according to kr also
/routes/index.py ; changed render_feed function to filter posts
/templates/base.html : Added some hidden fields in search bar form to manipulate url

Search feature completed

---

knowledge_repo/app/app.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/utils/s3_talk.py
knowledge_repo/repository.py

Description of changeset:
app.py - altered some urls to make it consistent with environment variables on devpolly.
polly_api.py - created add_kr function that calls functions to add kr to s3 and database.
s3_talk.py - added a function that adds en empty folder on s3 bucket for the kr.
repository.py - added a function that creates table in database for kr.

Add knowledge repository Feature

---

.circleci/config.yml

Description of changeset:
.circleci/config.yml - added profile in eb deploy

Deploy with profile

---

knowledge_repo/app/routes/index.py
knowledge_repo/app/templates/index-base.html
knowledge_repo/app/utils/posts.py

index.py - Changed some lines of code to make two commits compatible
utils/posts.py - Shifted kr filtering after pagination

Fix code dev

---

knowledge_repo/app/static/js/knowledge_typeahead.js
knowledge_repo/app/static/js/pages/base.js
knowledge_repo/app/static/js/tooltips.js

base.js and knowledge_typeahead.js
added key before the url and removed the function that converted '/' to '%2F' in url

Search bar bugs fixed

---

knowledge_repo/app/app.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/static/js/pages/add_post.js
knowledge_repo/app/templates/base.html
knowledge_repo/app/templates/upload_page.html

app.py - added new functions similar to get_kr_list() for convenience
polly_api.py - changed arguments for rendering upload page and added route for updating the dropdown after choosing a project
add_post.js - created new js file for sending ajax request and filling the dropdown of krs after selecting a project
base.html - added path for new js file
upload_page.html - reformatted code and added new dropdown for selecting project

Improve Add Post 

---

knowledge_repo/app/routes/tags.py
knowledge_repo/app/static/js/post-editor.js
knowledge_repo/app/templates/tag_pages.html

tags.py - Added code to filter posts further such that only user's/shared posts are shown
post-editor.js - corrected url to show default_thumbnail
tag_pages.html - corrected some more urls syntaxes

Fix searching on the basis of tags

---

knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/templates/upload_page.html

polly_api.py - path variable assignment fixed to add post correctly.
upload_page.html - Added checks if any info is not entered.

Add post bugs fixed

---

knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/templates/error.html
knowledge_repo/converter.py
knowledge_repo/post.py

Description of changeset:
polly_api.py - sending error message to frontend
error.html - if some error message is received from backend, then showing it
converter.py - Changing some error message and deleting all other formats than 'md', 'rmd' and ''ipynb' from registry

Error Handling in add post

---

knowledge_repo/app/templates/markdown-rendered.html

Fix Clicking tags after opening a post

---

knowledge_repo/app/routes/tags.py
knowledge_repo/app/utils/requests.py

Decoded url using a function instead of doing it manually

decoded url

---

knowledge_repo/app/routes/index.py
knowledge_repo/app/routes/polly_api.py
knowledge_repo/app/routes/posts.py
knowledge_repo/app/routes/tags.py
knowledge_repo/app/static/js/pages/base.js
knowledge_repo/app/templates/404.html
knowledge_repo/app/templates/base.html
knowledge_repo/app/templates/index-base.html
knowledge_repo/app/templates/index-cluster.html
knowledge_repo/app/templates/index-feed.html
knowledge_repo/app/templates/index-table.html
knowledge_repo/app/templates/markdown-base.html
knowledge_repo/app/templates/tag_pages.html
knowledge_repo/app/templates/upload_page.html

added '&repo=<repo>' in url at all reachable places

Fix switching views

---

knowledge_repo/app/app.py
knowledge_repo/app/templates/base.html

in base.html
added get_cognitodata function that gives GET request to '/userpool' and gets cognitodata.
if conditions added to check if polly or devpolly or testpolly, what is being used
slicing of hostname to remove 'kr' from 'kr.polly.elucidata.io'
changed path in cookies in the end

Fix internal server error dev

---

knowledge_repo/app/templates/markdown-rendered.html

merge changes + fixes for URL

---

knowledge_repo/app/static/js/index-cluster.js

Fix cluster groups dev

---

knowledge_repo/app/static/js/index-cluster.js
knowledge_repo/app/templates/index-cluster.html

Made KR and Repo variables available globally in JS

---

knowledge_repo/app/routes/index.py

Changes to make search work in the other two
